services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ygt-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: "bitnami/mongodb:latest"
    # image: "zcube/bitnami-compat-mongodb:latest" # use this image on Apple Silicon instead
    environment:
      MONGODB_ADVERTISED_HOSTNAME: 127.0.0.1
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/bitnami/mongodb

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    container_name: ygt-dev-mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-central-1
      - DEBUG=1
    volumes:
      - "./localstack:/tmp/localstack-ygt" # Persist data
      - "/var/run/docker.sock:/var/run/docker.sock" # Docker daemon socket

volumes:
  mongo-db:
  postgres-data:
